#ifndef SORO_MISSIONCONTROL_GLOBAL_H
#define SORO_MISSIONCONTROL_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(SORO_MISSIONCONTROL_LIBRARY)
#  define LIBSOROMC_EXPORT Q_DECL_EXPORT
#else
#  define LIBSOROMC_EXPORT Q_DECL_IMPORT
#endif

#endif // SORO_MISSIONCONTROL_GLOBAL_H
